services:

  server:
    build: server
    hostname: ovpn-server
    container_name: ovpn-server
    environment:
      PUBLIC_DNS: example.org
    command: run
    cap_add:
      - "NET_ADMIN"
    volumes:
      - ./docker-volumes/ovpn_server:/etc/openvpn

  gen_client:
    profiles:
      - client
    build: server
    command: new_client "${CLIENT_NAME}"
    volumes:
      - ./docker-volumes/ovpn_client:/ovpn_client
    volumes_from:
      - "server"
